package classics

type PoetryChar struct {
	Char      string `json:"char"`
	Pinyin    string `json:"pinyin"`
	Meaning   string `json:"meaning"`
	Work      string `json:"work"`
	Chapter   string `json:"chapter"`
	Sentence  string `json:"sentence"`
	Wuxing    string `json:"wuxing"`
	Gender    string `json:"gender"`
}

type PoetrySource struct {
	Name    string        `json:"name"`
	Chars   []PoetryChar  `json:"chars"`
}

var PoetrySources = map[string]PoetrySource{
	"诗经": {
		Name: "诗经",
		Chars: []PoetryChar{
			{Char: "思", Pinyin: "sī", Meaning: "思念", Work: "诗经", Chapter: "关雎", Sentence: "关关雎鸠，在河之洲", Wuxing: "金", Gender: "通用"},
			{Char: "悠", Pinyin: "yōu", Meaning: "悠长", Work: "诗经", Chapter: "关雎", Sentence: "悠哉悠哉，辗转反侧", Wuxing: "土", Gender: "通用"},
			{Char: "淑", Pinyin: "shū", Meaning: "善良", Work: "诗经", Chapter: "关雎", Sentence: "窈窕淑女，君子好逑", Wuxing: "水", Gender: "female"},
			{Char: "窈", Pinyin: "yǎo", Meaning: "文静", Work: "诗经", Chapter: "关雎", Sentence: "窈窕淑女，君子好逑", Wuxing: "土", Gender: "female"},
			{Char: "睢", Pinyin: "suī", Meaning: "和谐", Work: "诗经", Chapter: "关雎", Sentence: "关关雎鸠", Wuxing: "水", Gender: "通用"},
			{Char: "芩", Pinyin: "qín", Meaning: "坚韧", Work: "诗经", Chapter: "鹿鸣", Sentence: "呦呦鹿鸣，食野之芩", Wuxing: "木", Gender: "通用"},
			{Char: "鸣", Pinyin: "míng", Meaning: "鸣叫", Work: "诗经", Chapter: "鹿鸣", Sentence: "呦呦鹿鸣，食野之苹", Wuxing: "水", Gender: "通用"},
			{Char: "乔", Pinyin: "qiáo", Meaning: "高大", Work: "诗经", Chapter: "车舝", Sentence: "高山仰止，景行行止", Wuxing: "木", Gender: "male"},
			{Char: "蕙", Pinyin: "huì", Meaning: "兰草", Work: "诗经", Chapter: "郑风", Sentence: "溱与洧，方涣涣兮", Wuxing: "木", Gender: "female"},
			{Char: "兰", Pinyin: "lán", Meaning: "兰花", Work: "诗经", Chapter: "溱洧", Sentence: "维士与女，伊其相谑", Wuxing: "木", Gender: "通用"},
			{Char: "芍", Pinyin: "sháo", Meaning: "芍药", Work: "诗经", Chapter: "溱洧", Sentence: "维士与女，伊其相谑", Wuxing: "木", Gender: "female"},
			{Char: "清", Pinyin: "qīng", Meaning: "清澈", Work: "诗经", Chapter: "溱洧", Sentence: "溱与洧，方涣涣兮", Wuxing: "水", Gender: "通用"},
			{Char: "扬", Pinyin: "yáng", Meaning: "昂扬", Work: "诗经", Chapter: "溱洧", Sentence: "扬且之颜也", Wuxing: "火", Gender: "通用"},
			{Char: "舟", Pinyin: "zhōu", Meaning: "小船", Work: "诗经", Chapter: "柏舟", Sentence: "泛彼柏舟，亦泛其流", Wuxing: "金", Gender: "通用"},
			{Char: "柏", Pinyin: "bǎi", Meaning: "柏树", Work: "诗经", Chapter: "柏舟", Sentence: "泛彼柏舟，亦泛其流", Wuxing: "木", Gender: "通用"},
			{Char: "云", Pinyin: "yún", Meaning: "云彩", Work: "诗经", Chapter: "君子偕老", Sentence: "胡然而天也！胡然而帝也！", Wuxing: "水", Gender: "通用"},
			{Char: "归", Pinyin: "guī", Meaning: "归来", Work: "诗经", Chapter: "君子于役", Sentence: "君子于役，不日不月", Wuxing: "土", Gender: "通用"},
			{Char: "葛", Pinyin: "gě", Meaning: "葛藤", Work: "诗经", Chapter: "葛覃", Sentence: "葛之覃兮，施于中谷", Wuxing: "木", Gender: "通用"},
			{Char: "木", Pinyin: "mù", Meaning: "树木", Work: "诗经", Chapter: "葛覃", Sentence: "维叶萋萋，黄鸟于飞", Wuxing: "木", Gender: "通用"},
			{Char: "鸟", Pinyin: "niǎo", Meaning: "飞鸟", Work: "诗经", Chapter: "葛覃", Sentence: "黄鸟于飞，集于灌木", Wuxing: "火", Gender: "通用"},
			{Char: "羽", Pinyin: "yǔ", Meaning: "羽翼", Work: "诗经", Chapter: "鹿鸣", Sentence: "呦呦鹿鸣，食野之羽", Wuxing: "水", Gender: "通用"},
			{Char: "棘", Pinyin: "jí", Meaning: "酸枣", Work: "诗经", Chapter: "凯风", Sentence: "凯风自南，吹彼棘心", Wuxing: "木", Gender: "通用"},
			{Char: "桑", Pinyin: "sāng", Meaning: "桑树", Work: "诗经", Chapter: "桑中", Sentence: "期我乎桑中", Wuxing: "木", Gender: "通用"},
			{Char: "鹿", Pinyin: "lù", Meaning: "梅花鹿", Work: "诗经", Chapter: "鹿鸣", Sentence: "呦呦鹿鸣，食野之苹", Wuxing: "火", Gender: "通用"},
			{Char: "鹤", Pinyin: "hè", Meaning: "仙鹤", Work: "诗经", Chapter: "鹤鸣", Sentence: "鹤鸣于九皋，声闻于野", Wuxing: "水", Gender: "通用"},
			{Char: "渊", Pinyin: "yuān", Meaning: "深潭", Work: "诗经", Chapter: "鹤鸣", Sentence: "鱼潜在渊，或在于渚", Wuxing: "水", Gender: "通用"},
			{Char: "泉", Pinyin: "quán", Meaning: "泉水", Work: "诗经", Chapter: "鹤鸣", Sentence: "鱼潜在渊，或在于渚", Wuxing: "水", Gender: "通用"},
			{Char: "鱼", Pinyin: "yú", Meaning: "鱼儿", Work: "诗经", Chapter: "鱼藻", Sentence: "鱼在在藻，有颁其首", Wuxing: "水", Gender: "通用"},
			{Char: "藻", Pinyin: "zǎo", Meaning: "水藻", Work: "诗经", Chapter: "鱼藻", Sentence: "鱼在在藻，依于其蒲", Wuxing: "木", Gender: "通用"},
			{Char: "荷", Pinyin: "hé", Meaning: "荷花", Work: "诗经", Chapter: "泽陂", Sentence: "彼泽之陂，有蒲与荷", Wuxing: "木", Gender: "female"},
			{Char: "梅", Pinyin: "méi", Meaning: "梅花", Work: "诗经", Chapter: "摽有梅", Sentence: "摽有梅，其实七兮", Wuxing: "木", Gender: "female"},
			{Char: "桃", Pinyin: "táo", Meaning: "桃子", Work: "诗经", Chapter: "桃夭", Sentence: "桃之夭夭，灼灼其华", Wuxing: "木", Gender: "female"},
			{Char: "宜", Pinyin: "yí", Meaning: "适宜", Work: "诗经", Chapter: "桃夭", Sentence: "桃之夭夭，有蕡其实", Wuxing: "土", Gender: "通用"},
			{Char: "家", Pinyin: "jiā", Meaning: "家庭", Work: "诗经", Chapter: "桃夭", Sentence: "桃之夭夭，其叶蓁蓁", Wuxing: "木", Gender: "通用"},
			{Char: "风", Pinyin: "fēng", Meaning: "风", Work: "诗经", Chapter: "凯风", Sentence: "凯风自南，吹彼棘心", Wuxing: "水", Gender: "通用"},
			{Char: "凯", Pinyin: "kǎi", Meaning: "和乐", Work: "诗经", Chapter: "凯风", Sentence: "凯风自南，吹彼棘心", Wuxing: "木", Gender: "male"},
			{Char: "山", Pinyin: "shān", Meaning: "高山", Work: "诗经", Chapter: "节南山", Sentence: "节彼南山，维石岩岩", Wuxing: "土", Gender: "通用"},
			{Char: "川", Pinyin: "chuān", Meaning: "河流", Work: "诗经", Chapter: "节南山", Sentence: "节彼南山，惟石岩岩", Wuxing: "金", Gender: "通用"},
			{Char: "草", Pinyin: "cǎo", Meaning: "小草", Work: "诗经", Chapter: "野有蔓草", Sentence: "野有蔓草，零露漙兮", Wuxing: "木", Gender: "通用"},
			{Char: "露", Pinyin: "lù", Meaning: "雨露", Work: "诗经", Chapter: "野有蔓草", Sentence: "野有蔓草，零露瀼瀼", Wuxing: "水", Gender: "通用"},
			{Char: "苍", Pinyin: "cāng", Meaning: "青色", Work: "诗经", Chapter: "蒹葭", Sentence: "蒹葭苍苍，白露为霜", Wuxing: "木", Gender: "通用"},
			{Char: "霜", Pinyin: "shuāng", Meaning: "白霜", Work: "诗经", Chapter: "蒹葭", Sentence: "蒹葭苍苍，白露为霜", Wuxing: "水", Gender: "通用"},
			{Char: "葭", Pinyin: "jiā", Meaning: "芦苇", Work: "诗经", Chapter: "蒹葭", Sentence: "蒹葭苍苍，白露为霜", Wuxing: "木", Gender: "通用"},
			{Char: "采", Pinyin: "cǎi", Meaning: "采摘", Work: "诗经", Chapter: "采薇", Sentence: "采薇采薇，薇亦作止", Wuxing: "火", Gender: "通用"},
			{Char: "薇", Pinyin: "wēi", Meaning: "野豌豆", Work: "诗经", Chapter: "采薇", Sentence: "采薇采薇，薇亦作止", Wuxing: "木", Gender: "通用"},
			{Char: "柳", Pinyin: "liǔ", Meaning: "杨柳", Work: "诗经", Chapter: "采薇", Sentence: "昔我往矣，杨柳依依", Wuxing: "木", Gender: "通用"},
			{Char: "柔", Pinyin: "róu", Meaning: "柔软", Work: "诗经", Chapter: "采薇", Sentence: "昔我往矣，杨柳依依", Wuxing: "金", Gender: "female"},
			{Char: "星", Pinyin: "xīng", Meaning: "星星", Work: "诗经", Chapter: "绸缪", Sentence: "绸缪束薪，三星在天", Wuxing: "火", Gender: "通用"},
			{Char: "月", Pinyin: "yuè", Meaning: "月亮", Work: "诗经", Chapter: "月出", Sentence: "月出皎兮，佼人僚兮", Wuxing: "木", Gender: "通用"},
			{Char: "皎", Pinyin: "jiǎo", Meaning: "洁白", Work: "诗经", Chapter: "月出", Sentence: "月出皎兮，佼人僚兮", Wuxing: "木", Gender: "通用"},
			{Char: "皓", Pinyin: "hào", Meaning: "明亮", Work: "诗经", Chapter: "月出", Sentence: "月出皓兮，佼人懰兮", Wuxing: "木", Gender: "male"},
			{Char: "照", Pinyin: "zhào", Meaning: "照耀", Work: "诗经", Chapter: "月出", Sentence: "月出照兮，佼人燎兮", Wuxing: "火", Gender: "通用"},
			{Char: "泽", Pinyin: "zé", Meaning: "恩泽", Work: "诗经", Chapter: "泽陂", Sentence: "彼泽之陂，有蒲与蕳", Wuxing: "水", Gender: "通用"},
			{Char: "莲", Pinyin: "lián", Meaning: "莲花", Work: "诗经", Chapter: "泽陂", Sentence: "彼泽之陂，有蒲与莲", Wuxing: "木", Gender: "female"},
			{Char: "心", Pinyin: "xīn", Meaning: "内心", Work: "诗经", Chapter: "泽陂", Sentence: "彼泽之陂，有蒲菡萏", Wuxing: "金", Gender: "通用"},
			{Char: "静", Pinyin: "jìng", Meaning: "宁静", Work: "诗经", Chapter: "静女", Sentence: "静女其姝，俟我于城隅", Wuxing: "金", Gender: "female"},
			{Char: "女", Pinyin: "nǚ", Meaning: "女子", Work: "诗经", Chapter: "静女", Sentence: "静女其姝，俟我于城隅", Wuxing: "火", Gender: "female"},
			{Char: "彤", Pinyin: "tóng", Meaning: "红色", Work: "诗经", Chapter: "静女", Sentence: "彤管有炜，说怿女美", Wuxing: "火", Gender: "female"},
			{Char: "黄", Pinyin: "huáng", Meaning: "黄色", Work: "诗经", Chapter: "野有麂", Sentence: "野有麂，零露漙兮", Wuxing: "土", Gender: "通用"},
			{Char: "翰", Pinyin: "hàn", Meaning: "高飞", Work: "诗经", Chapter: "常棣", Sentence: "常棣之华，鄂不韡韡", Wuxing: "水", Gender: "male"},
			{Char: "飞", Pinyin: "fēi", Meaning: "飞翔", Work: "诗经", Chapter: "常棣", Sentence: "脊令在原，兄弟急难", Wuxing: "水", Gender: "通用"},
			{Char: "景", Pinyin: "jǐng", Meaning: "景色", Work: "诗经", Chapter: "车舝", Sentence: "高山仰止，景行行止", Wuxing: "木", Gender: "通用"},
			{Char: "行", Pinyin: "xíng", Meaning: "行走", Work: "诗经", Chapter: "车舝", Sentence: "高山仰止，景行行止", Wuxing: "金", Gender: "通用"},
			{Char: "德", Pinyin: "dé", Meaning: "品德", Work: "诗经", Chapter: "板", Sentence: "民之方殿屎，则莫我敢葵", Wuxing: "火", Gender: "通用"},
			{Char: "天", Pinyin: "tiān", Meaning: "天空", Work: "诗经", Chapter: "生民", Sentence: "厥初生民，时维姜嫄", Wuxing: "火", Gender: "通用"},
			{Char: "地", Pinyin: "dì", Meaning: "大地", Work: "诗经", Chapter: "生民", Sentence: "厥初生民，时维姜嫄", Wuxing: "土", Gender: "通用"},
			{Char: "神", Pinyin: "shén", Meaning: "神灵", Work: "诗经", Chapter: "生民", Sentence: "厥初生民，时维姜嫄", Wuxing: "金", Gender: "通用"},
			{Char: "灵", Pinyin: "líng", Meaning: "灵验", Work: "诗经", Chapter: "生民", Sentence: "上帝居歆，胡臭亶时", Wuxing: "火", Gender: "通用"},
			{Char: "生", Pinyin: "shēng", Meaning: "生命", Work: "诗经", Chapter: "生民", Sentence: "厥初生民，时维姜嫄", Wuxing: "金", Gender: "通用"},
			{Char: "福", Pinyin: "fú", Meaning: "福气", Work: "诗经", Chapter: "小明", Sentence: "明明上天，照临下土", Wuxing: "水", Gender: "通用"},
			{Char: "寿", Pinyin: "shòu", Meaning: "长寿", Work: "诗经", Chapter: "天保", Sentence: "天保定尔，俾尔戬谷", Wuxing: "金", Gender: "通用"},
			{Char: "昌", Pinyin: "chāng", Meaning: "昌盛", Work: "诗经", Chapter: "天保", Sentence: "天保定尔，俾尔戬谷", Wuxing: "火", Gender: "male"},
			{Char: "明", Pinyin: "míng", Meaning: "明亮", Work: "诗经", Chapter: "小明", Sentence: "明明上天，照临下土", Wuxing: "火", Gender: "通用"},
			{Char: "文", Pinyin: "wén", Meaning: "文化", Work: "诗经", Chapter: "宾之初筵", Sentence: "饮酒孔嘉，维其令仪", Wuxing: "水", Gender: "通用"},
			{Char: "武", Pinyin: "wǔ", Meaning: "武力", Work: "诗经", Chapter: "宾之初筵", Sentence: "既立之监，或佐之史", Wuxing: "水", Gender: "male"},
			{Char: "君", Pinyin: "jūn", Meaning: "君主", Work: "诗经", Chapter: "小明", Sentence: "明明上天，照临下土", Wuxing: "木", Gender: "male"},
			{Char: "子", Pinyin: "zǐ", Meaning: "子女", Work: "诗经", Chapter: "小明", Sentence: "嗟尔君子，无恒安息", Wuxing: "金", Gender: "通用"},
			{Char: "宇", Pinyin: "yǔ", Meaning: "宇宙", Work: "诗经", Chapter: "板", Sentence: "价人维藩，大师维垣", Wuxing: "土", Gender: "通用"},
			{Char: "维", Pinyin: "wéi", Meaning: "维护", Work: "诗经", Chapter: "节南山", Sentence: "节彼南山，维石岩岩", Wuxing: "土", Gender: "通用"},
			{Char: "石", Pinyin: "shí", Meaning: "石头", Work: "诗经", Chapter: "节南山", Sentence: "节彼南山，维石岩岩", Wuxing: "土", Gender: "通用"},
			{Char: "岩", Pinyin: "yán", Meaning: "岩石", Work: "诗经", Chapter: "节南山", Sentence: "节彼南山，维石岩岩", Wuxing: "土", Gender: "通用"},
			{Char: "允", Pinyin: "yǔn", Meaning: "诚信", Work: "诗经", Chapter: "小雅", Sentence: "允矣君子，展也大成", Wuxing: "土", Gender: "通用"},
			{Char: "大", Pinyin: "dà", Meaning: "广大", Work: "诗经", Chapter: "车舝", Sentence: "瞻彼日月，悠悠我思", Wuxing: "火", Gender: "通用"},
			{Char: "光", Pinyin: "guāng", Meaning: "光辉", Work: "诗经", Chapter: "小明", Sentence: "昔我往矣，日月方奥", Wuxing: "火", Gender: "通用"},
			{Char: "烈", Pinyin: "liè", Meaning: "猛烈", Work: "诗经", Chapter: "商颂", Sentence: "苞有三蘖，莫遂莫达", Wuxing: "火", Gender: "通用"},
			{Char: "显", Pinyin: "xiǎn", Meaning: "显耀", Work: "诗经", Chapter: "小明", Sentence: "明明上天，照临下土", Wuxing: "火", Gender: "通用"},
			{Char: "思", Pinyin: "sī", Meaning: "思念", Work: "诗经", Chapter: "子衿", Sentence: "青青子衿，悠悠我心", Wuxing: "金", Gender: "通用"},
			{Char: "悠", Pinyin: "yōu", Meaning: "悠长", Work: "诗经", Chapter: "子衿", Sentence: "青青子佩，悠悠我思", Wuxing: "土", Gender: "通用"},
			{Char: "佩", Pinyin: "pèi", Meaning: "佩戴", Work: "诗经", Chapter: "子衿", Sentence: "青青子佩，悠悠我思", Wuxing: "水", Gender: "通用"},
			{Char: "宁", Pinyin: "níng", Meaning: "安宁", Work: "诗经", Chapter: "子衿", Sentence: "挑兮达兮，在城阙兮", Wuxing: "火", Gender: "通用"},
			{Char: "盼", Pinyin: "pàn", Meaning: "盼望", Work: "诗经", Chapter: "硕人", Sentence: "巧笑倩兮，美目盼兮", Wuxing: "水", Gender: "通用"},
			{Char: "倩", Pinyin: "qiàn", Meaning: "美好", Work: "诗经", Chapter: "硕人", Sentence: "巧笑倩兮，美目盼兮", Wuxing: "金", Gender: "female"},
			{Char: "美", Pinyin: "měi", Meaning: "美丽", Work: "诗经", Chapter: "硕人", Sentence: "巧笑倩兮，美目盼兮", Wuxing: "水", Gender: "通用"},
			{Char: "柔", Pinyin: "róu", Meaning: "柔软", Work: "诗经", Chapter: "硕人", Sentence: "手如柔荑，肤如凝脂", Wuxing: "金", Gender: "female"},
			{Char: "手", Pinyin: "shǒu", Meaning: "手", Work: "诗经", Chapter: "硕人", Sentence: "手如柔荑，肤如凝脂", Wuxing: "金", Gender: "通用"},
			{Char: "如", Pinyin: "rú", Meaning: "如同", Work: "诗经", Chapter: "绸缪", Sentence: "绸缪束薪，三星在天", Wuxing: "土", Gender: "通用"},
			{Char: "薪", Pinyin: "xīn", Meaning: "柴火", Work: "诗经", Chapter: "绸缪", Sentence: "绸缪束薪，三星在天", Wuxing: "木", Gender: "通用"},
		},
	},
	"楚辞": {
		Name: "楚辞",
		Chars: []PoetryChar{
			{Char: "离", Pinyin: "lí", Meaning: "离别", Work: "楚辞", Chapter: "离骚", Sentence: "帝高阳之苗裔兮，朕皇考曰伯庸", Wuxing: "火", Gender: "通用"},
			{Char: "骚", Pinyin: "sāo", Meaning: "忧愁", Work: "楚辞", Chapter: "离骚", Sentence: "帝高阳之苗裔兮，朕皇考曰伯庸", Wuxing: "金", Gender: "通用"},
			{Char: "原", Pinyin: "yuán", Meaning: "本源", Work: "楚辞", Chapter: "离骚", Sentence: "名余曰正则兮，字余曰灵均", Wuxing: "木", Gender: "male"},
			{Char: "灵", Pinyin: "líng", Meaning: "神灵", Work: "楚辞", Chapter: "离骚", Sentence: "名余曰正则兮，字余曰灵均", Wuxing: "火", Gender: "通用"},
			{Char: "均", Pinyin: "jūn", Meaning: "平均", Work: "楚辞", Chapter: "离骚", Sentence: "名余曰正则兮，字余曰灵均", Wuxing: "土", Gender: "通用"},
			{Char: "正", Pinyin: "zhèng", Meaning: "正直", Work: "楚辞", Chapter: "离骚", Sentence: "名余曰正则兮，字余曰灵均", Wuxing: "火", Gender: "通用"},
			{Char: "则", Pinyin: "zé", Meaning: "法则", Work: "楚辞", Chapter: "离骚", Sentence: "名余曰正则兮，字余曰灵均", Wuxing: "火", Gender: "通用"},
			{Char: "修", Pinyin: "xiū", Meaning: "美好", Work: "楚辞", Chapter: "离骚", Sentence: "帝高阳之苗裔兮，朕皇考曰伯庸", Wuxing: "金", Gender: "通用"},
			{Char: "博", Pinyin: "bó", Meaning: "广博", Work: "楚辞", Chapter: "离骚", Sentence: "朝搴阰之木兰兮，夕揽洲之宿莽", Wuxing: "金", Gender: "通用"},
			{Char: "达", Pinyin: "dá", Meaning: "通达", Work: "楚辞", Chapter: "离骚", Sentence: "及年岁之未晏兮，时亦犹其未央", Wuxing: "火", Gender: "通用"},
			{Char: "贤", Pinyin: "xián", Meaning: "贤德", Work: "楚辞", Chapter: "离骚", Sentence: "举贤才而授能兮，循绳墨而不颇", Wuxing: "木", Gender: "通用"},
			{Char: "善", Pinyin: "shàn", Meaning: "善良", Work: "楚辞", Chapter: "离骚", Sentence: "亦余心之所善兮，虽九死其犹未悔", Wuxing: "金", Gender: "通用"},
			{Char: "美", Pinyin: "měi", Meaning: "美好", Work: "楚辞", Chapter: "离骚", Sentence: "既滋兰之九畹兮，又树蕙之百亩", Wuxing: "水", Gender: "通用"},
			{Char: "佳", Pinyin: "jiā", Meaning: "美好", Work: "楚辞", Chapter: "九歌", Sentence: "入不言兮出不辞，乘回风兮载云旗", Wuxing: "木", Gender: "通用"},
			{Char: "君", Pinyin: "jūn", Meaning: "君子", Work: "楚辞", Chapter: "离骚", Sentence: "指西海以为期兮，与重华游兮瑶之圃", Wuxing: "木", Gender: "male"},
			{Char: "子", Pinyin: "zǐ", Meaning: "儿子", Work: "楚辞", Chapter: "离骚", Sentence: "帝高阳之苗裔兮，朕皇考曰伯庸", Wuxing: "金", Gender: "通用"},
			{Char: "王", Pinyin: "wáng", Meaning: "帝王", Work: "楚辞", Chapter: "离骚", Sentence: "及年岁之未晏兮，时亦犹其未央", Wuxing: "土", Gender: "male"},
			{Char: "皇", Pinyin: "huáng", Meaning: "皇帝", Work: "楚辞", Chapter: "离骚", Sentence: "皇览葵余初度兮，肇锡余以嘉名", Wuxing: "金", Gender: "male"},
			{Char: "天", Pinyin: "tiān", Meaning: "天空", Work: "楚辞", Chapter: "离骚", Sentence: "指西海以为期兮", Wuxing: "火", Gender: "通用"},
			{Char: "地", Pinyin: "dì", Meaning: "大地", Work: "楚辞", Chapter: "离骚", Sentence: "及年岁之未晏兮，时亦犹其未央", Wuxing: "土", Gender: "通用"},
			{Char: "神", Pinyin: "shén", Meaning: "神灵", Work: "楚辞", Chapter: "九歌", Sentence: "广开兮天门，纷吾乘兮玄云", Wuxing: "金", Gender: "通用"},
			{Char: "魂", Pinyin: "hún", Meaning: "灵魂", Work: "楚辞", Chapter: "九歌", Sentence: "身既死兮神以灵，魂魄毅兮为鬼雄", Wuxing: "水", Gender: "通用"},
			{Char: "心", Pinyin: "xīn", Meaning: "内心", Work: "楚辞", Chapter: "离骚", Sentence: "亦余心之所善兮，虽九死其犹未悔", Wuxing: "金", Gender: "通用"},
			{Char: "志", Pinyin: "zhì", Meaning: "志向", Work: "楚辞", Chapter: "离骚", Sentence: "亦余心之所善兮，虽九死其犹未悔", Wuxing: "火", Gender: "通用"},
			{Char: "思", Pinyin: "sī", Meaning: "思念", Work: "楚辞", Chapter: "九歌", Sentence: "入不言兮出不辞，乘回风兮载云旗", Wuxing: "金", Gender: "通用"},
			{Char: "忧", Pinyin: "yōu", Meaning: "忧愁", Work: "楚辞", Chapter: "离骚", Sentence: "亦余心之所善兮，虽九死其犹未悔", Wuxing: "土", Gender: "通用"},
			{Char: "愁", Pinyin: "chóu", Meaning: "愁思", Work: "楚辞", Chapter: "九歌", Sentence: "悲莫悲兮生别离，乐莫乐兮新相知", Wuxing: "金", Gender: "通用"},
			{Char: "悲", Pinyin: "bēi", Meaning: "悲伤", Work: "楚辞", Chapter: "九歌", Sentence: "悲莫悲兮生别离，乐莫乐兮新相知", Wuxing: "水", Gender: "通用"},
			{Char: "哀", Pinyin: "āi", Meaning: "哀伤", Work: "楚辞", Chapter: "九歌", Sentence: "悲莫悲兮生别离，乐莫乐兮新相知", Wuxing: "土", Gender: "通用"},
			{Char: "壮", Pinyin: "zhuàng", Meaning: "雄壮", Work: "楚辞", Chapter: "九歌", Sentence: "身既死兮神以灵，魂魄毅兮为鬼雄", Wuxing: "土", Gender: "male"},
			{Char: "烈", Pinyin: "liè", Meaning: "刚烈", Work: "楚辞", Chapter: "九歌", Sentence: "身既死兮神以灵，魂魄毅兮为鬼雄", Wuxing: "火", Gender: "通用"},
			{Char: "武", Pinyin: "wǔ", Meaning: "英勇", Work: "楚辞", Chapter: "九歌", Sentence: "身既死兮神以灵，魂魄毅兮为鬼雄", Wuxing: "水", Gender: "male"},
			{Char: "忠", Pinyin: "zhōng", Meaning: "忠诚", Work: "楚辞", Chapter: "九歌", Sentence: "身既死兮神以灵，魂魄毅兮为鬼雄", Wuxing: "火", Gender: "通用"},
			{Char: "义", Pinyin: "yì", Meaning: "正义", Work: "楚辞", Chapter: "九歌", Sentence: "身既死兮神以灵，魂魄毅兮为鬼雄", Wuxing: "金", Gender: "通用"},
			{Char: "玉", Pinyin: "yù", Meaning: "美玉", Work: "楚辞", Chapter: "九歌", Sentence: "白玉兮为镇，疏石兰兮为芳", Wuxing: "木", Gender: "通用"},
			{Char: "桂", Pinyin: "guì", Meaning: "桂花", Work: "楚辞", Chapter: "九歌", Sentence: "桂栋兮兰橑，辛夷楣兮药房", Wuxing: "木", Gender: "通用"},
			{Char: "香", Pinyin: "xiāng", Meaning: "香气", Work: "楚辞", Chapter: "九歌", Sentence: "合百草兮实庭，建芳馨兮庑门", Wuxing: "水", Gender: "通用"},
			{Char: "芳", Pinyin: "fāng", Meaning: "芳香", Work: "楚辞", Chapter: "九歌", Sentence: "合百草兮实庭，建芳馨兮庑门", Wuxing: "木", Gender: "通用"},
			{Char: "兰", Pinyin: "lán", Meaning: "兰花", Work: "楚辞", Chapter: "九歌", Sentence: "桂栋兮兰橑，辛夷楣兮药房", Wuxing: "木", Gender: "通用"},
			{Char: "蕙", Pinyin: "huì", Meaning: "蕙兰", Work: "楚辞", Chapter: "离骚", Sentence: "既滋兰之九畹兮，又树蕙之百亩", Wuxing: "木", Gender: "female"},
			{Char: "芷", Pinyin: "zhǐ", Meaning: "白芷", Work: "楚辞", Chapter: "离骚", Sentence: "扈江离与辟芷兮，纫秋兰以为佩", Wuxing: "木", Gender: "通用"},
			{Char: "荷", Pinyin: "hé", Meaning: "荷花", Work: "楚辞", Chapter: "离骚", Sentence: "制芰荷以为衣兮，集芙蓉以为裳", Wuxing: "木", Gender: "通用"},
			{Char: "芙", Pinyin: "fú", Meaning: "芙蓉", Work: "楚辞", Chapter: "离骚", Sentence: "制芰荷以为衣兮，集芙蓉以为裳", Wuxing: "木", Gender: "通用"},
			{Char: "秋", Pinyin: "qiū", Meaning: "秋天", Work: "楚辞", Chapter: "九歌", Sentence: "袅袅兮秋风，洞庭波兮木叶下", Wuxing: "金", Gender: "通用"},
			{Char: "春", Pinyin: "chūn", Meaning: "春天", Work: "楚辞", Chapter: "楚辞", Sentence: "目极千里兮，伤春心", Wuxing: "木", Gender: "通用"},
			{Char: "冬", Pinyin: "dōng", Meaning: "冬天", Work: "楚辞", Chapter: "离骚", Sentence: "何所冬暖？何所夏寒？", Wuxing: "火", Gender: "通用"},
			{Char: "日", Pinyin: "rì", Meaning: "太阳", Work: "楚辞", Chapter: "离骚", Sentence: "朝发轫于苍梧兮，夕余至乎县圃", Wuxing: "火", Gender: "通用"},
			{Char: "月", Pinyin: "yuè", Meaning: "月亮", Work: "楚辞", Chapter: "离骚", Sentence: "及年岁之未晏兮，时亦犹其未央", Wuxing: "木", Gender: "通用"},
			{Char: "星", Pinyin: "xīng", Meaning: "星星", Work: "楚辞", Chapter: "九歌", Sentence: "星宫兮穆穆，乘龙兮辚辚", Wuxing: "火", Gender: "通用"},
			{Char: "云", Pinyin: "yún", Meaning: "云彩", Work: "楚辞", Chapter: "九歌", Sentence: "广开兮天门，纷吾乘兮玄云", Wuxing: "水", Gender: "通用"},
			{Char: "风", Pinyin: "fēng", Meaning: "风", Work: "楚辞", Chapter: "九歌", Sentence: "入不言兮出不辞，乘回风兮载云旗", Wuxing: "水", Gender: "通用"},
			{Char: "雨", Pinyin: "yǔ", Meaning: "雨水", Work: "楚辞", Chapter: "九歌", Sentence: "令飘风兮先驱，使冻雨兮洒尘", Wuxing: "水", Gender: "通用"},
			{Char: "雪", Pinyin: "xuě", Meaning: "雪花", Work: "楚辞", Chapter: "九章", Sentence: "霰雪纷其无垠兮，云霏霏而承宇", Wuxing: "水", Gender: "通用"},
			{Char: "山", Pinyin: "shān", Meaning: "高山", Work: "楚辞", Chapter: "离骚", Sentence: "朝发轫于苍梧兮，夕余至乎县圃", Wuxing: "土", Gender: "通用"},
			{Char: "川", Pinyin: "chuān", Meaning: "河流", Work: "楚辞", Chapter: "九歌", Sentence: "袅袅兮秋风，洞庭波兮木叶下", Wuxing: "金", Gender: "通用"},
			{Char: "水", Pinyin: "shuǐ", Meaning: "水", Work: "楚辞", Chapter: "九歌", Sentence: "袅袅兮秋风，洞庭波兮木叶下", Wuxing: "水", Gender: "通用"},
			{Char: "江", Pinyin: "jiāng", Meaning: "长江", Work: "楚辞", Chapter: "离骚", Sentence: "及年岁之未晏兮，时亦犹其未央", Wuxing: "水", Gender: "通用"},
			{Char: "海", Pinyin: "hǎi", Meaning: "大海", Work: "楚辞", Chapter: "离骚", Sentence: "指西海以为期兮，与重华游兮瑶之圃", Wuxing: "水", Gender: "通用"},
			{Char: "波", Pinyin: "bō", Meaning: "波浪", Work: "楚辞", Chapter: "九歌", Sentence: "袅袅兮秋风，洞庭波兮木叶下", Wuxing: "水", Gender: "通用"},
			{Char: "涛", Pinyin: "tāo", Meaning: "浪涛", Work: "楚辞", Chapter: "七谏", Sentence: "子胥谏而自躯兮，申不信而多受祸", Wuxing: "水", Gender: "通用"},
			{Char: "鸟", Pinyin: "niǎo", Meaning: "飞鸟", Work: "楚辞", Chapter: "离骚", Sentence: "涉青龙兮济腾翼，驾先乘兮得路", Wuxing: "火", Gender: "通用"},
			{Char: "凤", Pinyin: "fèng", Meaning: "凤凰", Work: "楚辞", Chapter: "离骚", Sentence: "驷玉虬以乘鹥兮，溘埃风余上征", Wuxing: "水", Gender: "通用"},
			{Char: "龙", Pinyin: "lóng", Meaning: "龙", Work: "楚辞", Chapter: "离骚", Sentence: "驷玉虬以乘鹥兮，溘埃风余上征", Wuxing: "火", Gender: "通用"},
			{Char: "鹤", Pinyin: "hè", Meaning: "仙鹤", Work: "楚辞", Chapter: "离骚", Sentence: "吾与重华游兮瑶之圃", Wuxing: "水", Gender: "通用"},
			{Char: "鸿", Pinyin: "hóng", Meaning: "鸿雁", Work: "楚辞", Chapter: "七谏", Sentence: "联蕙芷以为佩兮，过鲍肆而失香", Wuxing: "水", Gender: "通用"},
			{Char: "飞", Pinyin: "fēi", Meaning: "飞翔", Work: "楚辞", Chapter: "离骚", Sentence: "吾令凤鸟飞腾兮，继之以日夜", Wuxing: "水", Gender: "通用"},
			{Char: "腾", Pinyin: "téng", Meaning: "腾飞", Work: "楚辞", Chapter: "离骚", Sentence: "吾令凤鸟飞腾兮，继之以日夜", Wuxing: "火", Gender: "通用"},
			{Char: "游", Pinyin: "yóu", Meaning: "游玩", Work: "楚辞", Chapter: "离骚", Sentence: "吾与重华游兮瑶之圃", Wuxing: "水", Gender: "通用"},
			{Char: "章", Pinyin: "zhāng", Meaning: "文章", Work: "楚辞", Chapter: "离骚", Sentence: "及年岁之未晏兮，时亦犹其未央", Wuxing: "火", Gender: "通用"},
			{Char: "文", Pinyin: "wén", Meaning: "文化", Work: "楚辞", Chapter: "九歌", Sentence: "广开兮天门，纷吾乘兮玄云", Wuxing: "水", Gender: "通用"},
			{Char: "武", Pinyin: "wǔ", Meaning: "武力", Work: "楚辞", Chapter: "国殇", Sentence: "诚既勇兮又以武，终刚强兮不可凌", Wuxing: "水", Gender: "male"},
			{Char: "华", Pinyin: "huá", Meaning: "华丽", Work: "楚辞", Chapter: "离骚", Sentence: "及年岁之未晏兮，时亦犹其未央", Wuxing: "水", Gender: "通用"},
			{Char: "英", Pinyin: "yīng", Meaning: "英雄", Work: "楚辞", Chapter: "离骚", Sentence: "及年岁之未晏兮，时亦犹其未央", Wuxing: "木", Gender: "通用"},
			{Char: "雄", Pinyin: "xióng", Meaning: "雄伟", Work: "楚辞", Chapter: "九歌", Sentence: "身既死兮神以灵，魂魄毅兮为鬼雄", Wuxing: "水", Gender: "male"},
			{Char: "俊", Pinyin: "jùn", Meaning: "俊秀", Work: "楚辞", Chapter: "九歌", Sentence: "灵偃蹇兮姣服，芳菲菲兮满堂", Wuxing: "火", Gender: "通用"},
			{Char: "杰", Pinyin: "jié", Meaning: "杰出", Work: "楚辞", Chapter: "离骚", Sentence: "及年岁之未晏兮，时亦犹其未央", Wuxing: "木", Gender: "通用"},
			{Char: "圣", Pinyin: "shèng", Meaning: "圣明", Work: "楚辞", Chapter: "离骚", Sentence: "夫维圣哲以茂行兮，苟得用此下土", Wuxing: "土", Gender: "通用"},
			{Char: "哲", Pinyin: "zhé", Meaning: "智慧", Work: "楚辞", Chapter: "离骚", Sentence: "夫维圣哲以茂行兮，苟得用此下土", Wuxing: "火", Gender: "通用"},
			{Char: "明", Pinyin: "míng", Meaning: "明亮", Work: "楚辞", Chapter: "离骚", Sentence: "及年岁之未晏兮，时亦犹其未央", Wuxing: "火", Gender: "通用"},
			{Char: "朗", Pinyin: "lǎng", Meaning: "明朗", Work: "楚辞", Chapter: "九歌", Sentence: "灵连蜷兮既留，烂昭昭兮未央", Wuxing: "火", Gender: "通用"},
			{Char: "昭", Pinyin: "zhāo", Meaning: "明亮", Work: "楚辞", Chapter: "九歌", Sentence: "灵连蜷兮既留，烂昭昭兮未央", Wuxing: "火", Gender: "通用"},
			{Char: "光", Pinyin: "guāng", Meaning: "光辉", Work: "楚辞", Chapter: "九歌", Sentence: "广开兮天门，纷吾乘兮玄云", Wuxing: "火", Gender: "通用"},
			{Char: "辉", Pinyin: "huī", Meaning: "辉煌", Work: "楚辞", Chapter: "离骚", Sentence: "及年岁之未晏兮，时亦犹其未央", Wuxing: "水", Gender: "通用"},
			{Char: "宇", Pinyin: "yǔ", Meaning: "宇宙", Work: "楚辞", Chapter: "九歌", Sentence: "灵皇皇兮既降，猋远举兮云中", Wuxing: "土", Gender: "通用"},
			{Char: "昊", Pinyin: "hào", Meaning: "天空", Work: "楚辞", Chapter: "九歌", Sentence: "灵皇皇兮既降，猋远举兮云中", Wuxing: "火", Gender: "通用"},
			{Char: "苍", Pinyin: "cāng", Meaning: "苍天", Work: "楚辞", Chapter: "九歌", Sentence: "灵皇皇兮既降，猋远举兮云中", Wuxing: "木", Gender: "通用"},
		},
	},
	"唐诗": {
		Name: "唐诗",
		Chars: []PoetryChar{
			{Char: "明", Pinyin: "míng", Meaning: "明亮", Work: "唐诗", Chapter: "静夜思", Sentence: "床前明月光，疑是地上霜", Wuxing: "火", Gender: "通用"},
			{Char: "月", Pinyin: "yuè", Meaning: "月亮", Work: "唐诗", Chapter: "静夜思", Sentence: "床前明月光，疑是地上霜", Wuxing: "木", Gender: "通用"},
			{Char: "光", Pinyin: "guāng", Meaning: "光辉", Work: "唐诗", Chapter: "静夜思", Sentence: "床前明月光，疑是地上霜", Wuxing: "火", Gender: "通用"},
			{Char: "霜", Pinyin: "shuāng", Meaning: "白霜", Work: "唐诗", Chapter: "静夜思", Sentence: "床前明月光，疑是地上霜", Wuxing: "水", Gender: "通用"},
			{Char: "思", Pinyin: "sī", Meaning: "思念", Work: "唐诗", Chapter: "静夜思", Sentence: "举头望明月，低头思故乡", Wuxing: "金", Gender: "通用"},
			{Char: "乡", Pinyin: "xiāng", Meaning: "故乡", Work: "唐诗", Chapter: "静夜思", Sentence: "举头望明月，低头思故乡", Wuxing: "水", Gender: "通用"},
			{Char: "春", Pinyin: "chūn", Meaning: "春天", Work: "唐诗", Chapter: "春晓", Sentence: "春眠不觉晓，处处闻啼鸟", Wuxing: "木", Gender: "通用"},
			{Char: "眠", Pinyin: "mián", Meaning: "睡眠", Work: "唐诗", Chapter: "春晓", Sentence: "春眠不觉晓，处处闻啼鸟", Wuxing: "水", Gender: "通用"},
			{Char: "晓", Pinyin: "xiǎo", Meaning: "早晨", Work: "唐诗", Chapter: "春晓", Sentence: "春眠不觉晓，处处闻啼鸟", Wuxing: "火", Gender: "通用"},
			{Char: "鸟", Pinyin: "niǎo", Meaning: "鸟", Work: "唐诗", Chapter: "春晓", Sentence: "春眠不觉晓，处处闻啼鸟", Wuxing: "火", Gender: "通用"},
			{Char: "夜", Pinyin: "yè", Meaning: "夜晚", Work: "唐诗", Chapter: "春晓", Sentence: "夜来风雨声，花落知多少", Wuxing: "火", Gender: "通用"},
			{Char: "风", Pinyin: "fēng", Meaning: "风", Work: "唐诗", Chapter: "春晓", Sentence: "夜来风雨声，花落知多少", Wuxing: "水", Gender: "通用"},
			{Char: "雨", Pinyin: "yǔ", Meaning: "雨", Work: "唐诗", Chapter: "春晓", Sentence: "夜来风雨声，花落知多少", Wuxing: "水", Gender: "通用"},
			{Char: "花", Pinyin: "huā", Meaning: "花", Work: "唐诗", Chapter: "春晓", Sentence: "夜来风雨声，花落知多少", Wuxing: "木", Gender: "通用"},
			{Char: "落", Pinyin: "luò", Meaning: "落下", Work: "唐诗", Chapter: "春晓", Sentence: "夜来风雨声，花落知多少", Wuxing: "木", Gender: "通用"},
			{Char: "白", Pinyin: "bái", Meaning: "白色", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "白日依山尽，黄河入海流", Wuxing: "水", Gender: "通用"},
			{Char: "日", Pinyin: "rì", Meaning: "太阳", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "白日依山尽，黄河入海流", Wuxing: "火", Gender: "通用"},
			{Char: "山", Pinyin: "shān", Meaning: "高山", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "白日依山尽，黄河入海流", Wuxing: "土", Gender: "通用"},
			{Char: "河", Pinyin: "hé", Meaning: "黄河", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "白日依山尽，黄河入海流", Wuxing: "水", Gender: "通用"},
			{Char: "海", Pinyin: "hǎi", Meaning: "大海", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "白日依山尽，黄河入海流", Wuxing: "水", Gender: "通用"},
			{Char: "流", Pinyin: "liú", Meaning: "流动", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "白日依山尽，黄河入海流", Wuxing: "水", Gender: "通用"},
			{Char: "欲", Pinyin: "yù", Meaning: "欲望", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "欲穷千里目，更上一层楼", Wuxing: "金", Gender: "通用"},
			{Char: "穷", Pinyin: "qióng", Meaning: "穷尽", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "欲穷千里目，更上一层楼", Wuxing: "木", Gender: "通用"},
			{Char: "千", Pinyin: "qiān", Meaning: "千", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "欲穷千里目，更上一层楼", Wuxing: "金", Gender: "通用"},
			{Char: "里", Pinyin: "lǐ", Meaning: "里程", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "欲穷千里目，更上一层楼", Wuxing: "土", Gender: "通用"},
			{Char: "目", Pinyin: "mù", Meaning: "眼睛", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "欲穷千里目，更上一层楼", Wuxing: "水", Gender: "通用"},
			{Char: "更", Pinyin: "gēng", Meaning: "更加", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "欲穷千里目，更上一层楼", Wuxing: "土", Gender: "通用"},
			{Char: "上", Pinyin: "shàng", Meaning: "上面", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "欲穷千里目，更上一层楼", Wuxing: "金", Gender: "通用"},
			{Char: "楼", Pinyin: "lóu", Meaning: "楼", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "欲穷千里目，更上一层楼", Wuxing: "木", Gender: "通用"},
			{Char: "红豆", Pinyin: "hóngdòu", Meaning: "红豆", Work: "唐诗", Chapter: "相思", Sentence: "红豆生南国，春来发几枝", Wuxing: "火", Gender: "通用"},
			{Char: "南", Pinyin: "nán", Meaning: "南方", Work: "唐诗", Chapter: "相思", Sentence: "红豆生南国，春来发几枝", Wuxing: "火", Gender: "通用"},
			{Char: "国", Pinyin: "guó", Meaning: "国家", Work: "唐诗", Chapter: "相思", Sentence: "红豆生南国，春来发几枝", Wuxing: "木", Gender: "通用"},
			{Char: "春", Pinyin: "chūn", Meaning: "春天", Work: "唐诗", Chapter: "相思", Sentence: "红豆生南国，春来发几枝", Wuxing: "木", Gender: "通用"},
			{Char: "发", Pinyin: "fā", Meaning: "生长", Work: "唐诗", Chapter: "相思", Sentence: "红豆生南国，春来发几枝", Wuxing: "水", Gender: "通用"},
			{Char: "枝", Pinyin: "zhī", Meaning: "枝条", Work: "唐诗", Chapter: "相思", Sentence: "红豆生南国，春来发几枝", Wuxing: "木", Gender: "通用"},
			{Char: "愿", Pinyin: "yuàn", Meaning: "愿望", Work: "唐诗", Chapter: "相思", Sentence: "愿君多采撷，此物最相思", Wuxing: "木", Gender: "通用"},
			{Char: "君", Pinyin: "jūn", Meaning: "你", Work: "唐诗", Chapter: "相思", Sentence: "愿君多采撷，此物最相思", Wuxing: "木", Gender: "通用"},
			{Char: "采", Pinyin: "cǎi", Meaning: "采摘", Work: "唐诗", Chapter: "相思", Sentence: "愿君多采撷，此物最相思", Wuxing: "火", Gender: "通用"},
			{Char: "最", Pinyin: "zuì", Meaning: "最", Work: "唐诗", Chapter: "相思", Sentence: "愿君多采撷，此物最相思", Wuxing: "火", Gender: "通用"},
			{Char: "慈", Pinyin: "cí", Meaning: "慈爱", Work: "唐诗", Chapter: "游子吟", Sentence: "慈母手中线，游子身上衣", Wuxing: "金", Gender: "通用"},
			{Char: "母", Pinyin: "mǔ", Meaning: "母亲", Work: "唐诗", Chapter: "游子吟", Sentence: "慈母手中线，游子身上衣", Wuxing: "水", Gender: "通用"},
			{Char: "手", Pinyin: "shǒu", Meaning: "手", Work: "唐诗", Chapter: "游子吟", Sentence: "慈母手中线，游子身上衣", Wuxing: "金", Gender: "通用"},
			{Char: "中", Pinyin: "zhōng", Meaning: "中间", Work: "唐诗", Chapter: "游子吟", Sentence: "慈母手中线，游子身上衣", Wuxing: "火", Gender: "通用"},
			{Char: "线", Pinyin: "xiàn", Meaning: "线", Work: "唐诗", Chapter: "游子吟", Sentence: "慈母手中线，游子身上衣", Wuxing: "金", Gender: "通用"},
			{Char: "游", Pinyin: "yóu", Meaning: "游子", Work: "唐诗", Chapter: "游子吟", Sentence: "慈母手中线，游子身上衣", Wuxing: "水", Gender: "通用"},
			{Char: "身", Pinyin: "shēn", Meaning: "身体", Work: "唐诗", Chapter: "游子吟", Sentence: "慈母手中线，游子身上衣", Wuxing: "金", Gender: "通用"},
			{Char: "衣", Pinyin: "yī", Meaning: "衣服", Work: "唐诗", Chapter: "游子吟", Sentence: "慈母手中线，游子身上衣", Wuxing: "土", Gender: "通用"},
			{Char: "临", Pinyin: "lín", Meaning: "来到", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "白日依山尽，黄河入海流", Wuxing: "火", Gender: "通用"},
			{Char: "黄", Pinyin: "huáng", Meaning: "黄色", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "白日依山尽，黄河入海流", Wuxing: "土", Gender: "通用"},
			{Char: "入", Pinyin: "rù", Meaning: "进入", Work: "唐诗", Chapter: "登鹳雀楼", Sentence: "白日依山尽，黄河入海流", Wuxing: "金", Gender: "通用"},
			{Char: "碧", Pinyin: "bì", Meaning: "碧绿", Work: "唐诗", Chapter: "送元二", Sentence: "渭城朝雨浥轻尘，客舍青青柳色新", Wuxing: "水", Gender: "通用"},
			{Char: "城", Pinyin: "chéng", Meaning: "城市", Work: "唐诗", Chapter: "送元二", Sentence: "渭城朝雨浥轻尘，客舍青青柳色新", Wuxing: "土", Gender: "通用"},
			{Char: "朝", Pinyin: "zhāo", Meaning: "早晨", Work: "唐诗", Chapter: "送元二", Sentence: "渭城朝雨浥轻尘，客舍青青柳色新", Wuxing: "金", Gender: "通用"},
			{Char: "雨", Pinyin: "yǔ", Meaning: "雨", Work: "唐诗", Chapter: "送元二", Sentence: "渭城朝雨浥轻尘，客舍青青柳色新", Wuxing: "水", Gender: "通用"},
			{Char: "柳", Pinyin: "liǔ", Meaning: "杨柳", Work: "唐诗", Chapter: "送元二", Sentence: "渭城朝雨浥轻尘，客舍青青柳色新", Wuxing: "木", Gender: "通用"},
			{Char: "色", Pinyin: "sè", Meaning: "颜色", Work: "唐诗", Chapter: "送元二", Sentence: "渭城朝雨浥轻尘，客舍青青柳色新", Wuxing: "金", Gender: "通用"},
			{Char: "新", Pinyin: "xīn", Meaning: "新", Work: "唐诗", Chapter: "送元二", Sentence: "渭城朝雨浥轻尘，客舍青青柳色新", Wuxing: "金", Gender: "通用"},
			{Char: "青", Pinyin: "qīng", Meaning: "青色", Work: "唐诗", Chapter: "送元二", Sentence: "渭城朝雨浥轻尘，客舍青青柳色新", Wuxing: "金", Gender: "通用"},
			{Char: "劝", Pinyin: "quàn", Meaning: "劝", Work: "唐诗", Chapter: "送元二", Sentence: "劝君更尽一杯酒，西出阳关无故人", Wuxing: "金", Gender: "通用"},
			{Char: "更", Pinyin: "gèng", Meaning: "更加", Work: "唐诗", Chapter: "送元二", Sentence: "劝君更尽一杯酒，西出阳关无故人", Wuxing: "土", Gender: "通用"},
			{Char: "杯", Pinyin: "bēi", Meaning: "杯子", Work: "唐诗", Chapter: "送元二", Sentence: "劝君更尽一杯酒，西出阳关无故人", Wuxing: "水", Gender: "通用"},
			{Char: "酒", Pinyin: "jiǔ", Meaning: "酒", Work: "唐诗", Chapter: "送元二", Sentence: "劝君更尽一杯酒，西出阳关无故人", Wuxing: "水", Gender: "通用"},
			{Char: "西", Pinyin: "xī", Meaning: "西方", Work: "唐诗", Chapter: "送元二", Sentence: "劝君更尽一杯酒，西出阳关无故人", Wuxing: "金", Gender: "通用"},
			{Char: "阳", Pinyin: "yáng", Meaning: "阳光", Work: "唐诗", Chapter: "送元二", Sentence: "劝君更尽一杯酒，西出阳关无故人", Wuxing: "土", Gender: "通用"},
			{Char: "故", Pinyin: "gù", Meaning: "故人", Work: "唐诗", Chapter: "送元二", Sentence: "劝君更尽一杯酒，西出阳关无故人", Wuxing: "火", Gender: "通用"},
			{Char: "人", Pinyin: "rén", Meaning: "人", Work: "唐诗", Chapter: "送元二", Sentence: "劝君更尽一杯酒，西出阳关无故人", Wuxing: "金", Gender: "通用"},
		},
	},
}

func GetPoetryCharList(source string) []PoetryChar {
	if source == "" {
		var allChars []PoetryChar
		for _, ps := range PoetrySources {
			allChars = append(allChars, ps.Chars...)
		}
		return allChars
	}
	if ps, ok := PoetrySources[source]; ok {
		return ps.Chars
	}
	return nil
}

func GetPoetrySourceNames() []string {
	return []string{"诗经", "楚辞", "唐诗", "宋词", "乐府", "古文名句"}
}

type GuwenMingju struct {
	Char     string `json:"char"`
	Pinyin  string `json:"pinyin"`
	Meaning string `json:"meaning"`
	Source  string `json:"source"`
	Sentence string `json:"sentence"`
	Wuxing  string `json:"wuxing"`
	Gender  string `json:"gender"`
}

var GuwenMingjuChars = []GuwenMingju{
	{Char: "悦", Pinyin: "yuè", Meaning: "喜悦、愉快", Source: "越人歌", Sentence: "山有木兮木有枝，心悦君兮君不知", Wuxing: "金", Gender: "通用"},
	{Char: "君", Pinyin: "jūn", Meaning: "君子、君主", Source: "越人歌", Sentence: "山有木兮木有枝，心悦君兮君不知", Wuxing: "木", Gender: "通用"},
	{Char: "知", Pinyin: "zhī", Meaning: "知道、了解", Source: "越人歌", Sentence: "山有木兮木有枝，心悦君兮君不知", Wuxing: "火", Gender: "通用"},
	{Char: "枝", Pinyin: "zhī", Meaning: "枝条", Source: "越人歌", Sentence: "山有木兮木有枝，心悦君兮君不知", Wuxing: "木", Gender: "通用"},
	{Char: "木", Pinyin: "mù", Meaning: "树木", Source: "越人歌", Sentence: "山有木兮木有枝，心悦君兮君不知", Wuxing: "木", Gender: "通用"},
	{Char: "山", Pinyin: "shān", Meaning: "高山", Source: "越人歌", Sentence: "山有木兮木有枝，心悦君兮君不知", Wuxing: "土", Gender: "通用"},
	{Char: "兮", Pinyin: "xī", Meaning: "语气词", Source: "越人歌", Sentence: "山有木兮木有枝，心悦君兮君不知", Wuxing: "金", Gender: "通用"},
	{Char: "润", Pinyin: "rùn", Meaning: "滋润、润泽", Source: "论语", Sentence: "为政以德，譬如北辰，居其所而众星共之", Wuxing: "水", Gender: "通用"},
	{Char: "德", Pinyin: "dé", Meaning: "品德、德行", Source: "论语", Sentence: "为政以德，譬如北辰，居其所而众星共之", Wuxing: "火", Gender: "通用"},
	{Char: "政", Pinyin: "zhèng", Meaning: "政治、政务", Source: "论语", Sentence: "为政以德，譬如北辰，居其所而众星共之", Wuxing: "火", Gender: "通用"},
	{Char: "北", Pinyin: "běi", Meaning: "北方", Source: "论语", Sentence: "为政以德，譬如北辰，居其所而众星共之", Wuxing: "水", Gender: "通用"},
	{Char: "辰", Pinyin: "chén", Meaning: "星辰、时光", Source: "论语", Sentence: "为政以德，譬如北辰，居其所而众星共之", Wuxing: "土", Gender: "通用"},
	{Char: "众", Pinyin: "zhòng", Meaning: "众多、众人", Source: "论语", Sentence: "为政以德，譬如北辰，居其所而众星共之", Wuxing: "火", Gender: "通用"},
	{Char: "星", Pinyin: "xīng", Meaning: "星星", Source: "论语", Sentence: "为政以德，譬如北辰，居其所而众星共之", Wuxing: "火", Gender: "通用"},
	{Char: "共", Pinyin: "gòng", Meaning: "共同", Source: "论语", Sentence: "为政以德，譬如北辰，居其所而众星共之", Wuxing: "木", Gender: "通用"},
	{Char: "学", Pinyin: "xué", Meaning: "学习、学问", Source: "论语", Sentence: "学而时习之，不亦说乎", Wuxing: "水", Gender: "通用"},
	{Char: "习", Pinyin: "xí", Meaning: "复习、练习", Source: "论语", Sentence: "学而时习之，不亦说乎", Wuxing: "金", Gender: "通用"},
	{Char: "说", Pinyin: "yuè", Meaning: "喜悦", Source: "论语", Sentence: "学而时习之，不亦说乎", Wuxing: "金", Gender: "通用"},
	{Char: "时", Pinyin: "shí", Meaning: "时间、时常", Source: "论语", Sentence: "学而时习之，不亦说乎", Wuxing: "金", Gender: "通用"},
	{Char: "而", Pinyin: "ér", Meaning: "而且、然而", Source: "论语", Sentence: "学而时习之，不亦说乎", Wuxing: "火", Gender: "通用"},
	{Char: "有", Pinyin: "yǒu", Meaning: "拥有", Source: "论语", Sentence: "学而时习之，不亦说乎", Wuxing: "土", Gender: "通用"},
	{Char: "朋", Pinyin: "péng", Meaning: "朋友", Source: "论语", Sentence: "有朋自远方来，不亦乐乎", Wuxing: "木", Gender: "通用"},
	{Char: "远", Pinyin: "yuǎn", Meaning: "远方", Source: "论语", Sentence: "有朋自远方来，不亦乐乎", Wuxing: "土", Gender: "通用"},
	{Char: "方", Pinyin: "fāng", Meaning: "方向、地方", Source: "论语", Sentence: "有朋自远方来，不亦乐乎", Wuxing: "水", Gender: "通用"},
	{Char: "来", Pinyin: "lái", Meaning: "来到", Source: "论语", Sentence: "有朋自远方来，不亦乐乎", Wuxing: "木", Gender: "通用"},
	{Char: "乐", Pinyin: "lè", Meaning: "快乐", Source: "论语", Sentence: "有朋自远方来，不亦乐乎", Wuxing: "火", Gender: "通用"},
	{Char: "温", Pinyin: "wēn", Meaning: "温和、温暖", Source: "论语", Sentence: "温故而知新，可以为师矣", Wuxing: "水", Gender: "通用"},
	{Char: "故", Pinyin: "gù", Meaning: "过去、故事", Source: "论语", Sentence: "温故而知新，可以为师矣", Wuxing: "火", Gender: "通用"},
	{Char: "新", Pinyin: "xīn", Meaning: "新的", Source: "论语", Sentence: "温故而知新，可以为师矣", Wuxing: "金", Gender: "通用"},
	{Char: "师", Pinyin: "shī", Meaning: "老师、师父", Source: "论语", Sentence: "温故而知新，可以为师矣", Wuxing: "金", Gender: "通用"},
	{Char: "知", Pinyin: "zhī", Meaning: "知道、知识", Source: "论语", Sentence: "温故而知新，可以为师矣", Wuxing: "火", Gender: "通用"},
	{Char: "仁", Pinyin: "rén", Meaning: "仁爱、仁慈", Source: "论语", Sentence: "君子务本，本立而道生", Wuxing: "金", Gender: "通用"},
	{Char: "本", Pinyin: "běn", Meaning: "根本", Source: "论语", Sentence: "君子务本，本立而道生", Wuxing: "木", Gender: "通用"},
	{Char: "道", Pinyin: "dào", Meaning: "道理、道路", Source: "论语", Sentence: "君子务本，本立而道生", Wuxing: "火", Gender: "通用"},
	{Char: "生", Pinyin: "shēng", Meaning: "生命、生长", Source: "论语", Sentence: "君子务本，本立而道生", Wuxing: "金", Gender: "通用"},
	{Char: "孝", Pinyin: "xiào", Meaning: "孝顺", Source: "论语", Sentence: "君子务本，本立而道生", Wuxing: "水", Gender: "通用"},
	{Char: "弟", Pinyin: "dì", Meaning: "兄弟、悌", Source: "论语", Sentence: "君子务本，本立而道生", Wuxing: "火", Gender: "通用"},
	{Char: "信", Pinyin: "xìn", Meaning: "诚信、信任", Source: "论语", Sentence: "君子务本，本立而道生", Wuxing: "金", Gender: "通用"},
	{Char: "忠", Pinyin: "zhōng", Meaning: "忠诚", Source: "论语", Sentence: "君子务本，本立而道生", Wuxing: "火", Gender: "通用"},
	{Char: "礼", Pinyin: "lǐ", Meaning: "礼节、礼貌", Source: "论语", Sentence: "君子务本，本立而道生", Wuxing: "火", Gender: "通用"},
	{Char: "和", Pinyin: "hé", Meaning: "和谐、和平", Source: "论语", Sentence: "礼之用，和为贵", Wuxing: "水", Gender: "通用"},
	{Char: "贵", Pinyin: "guì", Meaning: "珍贵、尊贵", Source: "论语", Sentence: "礼之用，和为贵", Wuxing: "木", Gender: "通用"},
	{Char: "用", Pinyin: "yòng", Meaning: "使用、作用", Source: "论语", Sentence: "礼之用，和为贵", Wuxing: "土", Gender: "通用"},
	{Char: "善", Pinyin: "shàn", Meaning: "善良、善于", Source: "论语", Sentence: "君子以文会友，以友辅仁", Wuxing: "金", Gender: "通用"},
	{Char: "文", Pinyin: "wén", Meaning: "文化、文章", Source: "论语", Sentence: "君子以文会友，以友辅仁", Wuxing: "水", Gender: "通用"},
	{Char: "友", Pinyin: "yǒu", Meaning: "朋友", Source: "论语", Sentence: "君子以文会友，以友辅仁", Wuxing: "土", Gender: "通用"},
	{Char: "辅", Pinyin: "fǔ", Meaning: "辅助", Source: "论语", Sentence: "君子以文会友，以友辅仁", Wuxing: "土", Gender: "通用"},
	{Char: "见", Pinyin: "jiàn", Meaning: "看见、见解", Source: "论语", Sentence: "见贤思齐焉，见不贤而内自省也", Wuxing: "金", Gender: "通用"},
	{Char: "贤", Pinyin: "xián", Meaning: "贤德、贤才", Source: "论语", Sentence: "见贤思齐焉，见不贤而内自省也", Wuxing: "木", Gender: "通用"},
	{Char: "思", Pinyin: "sī", Meaning: "思考、思念", Source: "论语", Sentence: "见贤思齐焉，见不贤而内自省也", Wuxing: "金", Gender: "通用"},
	{Char: "齐", Pinyin: "qí", Meaning: "整齐、齐心", Source: "论语", Sentence: "见贤思齐焉，见不贤而内自省也", Wuxing: "金", Gender: "通用"},
	{Char: "省", Pinyin: "xǐng", Meaning: "反省", Source: "论语", Sentence: "见贤思齐焉，见不贤而内自省也", Wuxing: "金", Gender: "通用"},
	{Char: "义", Pinyin: "yì", Meaning: "正义、义理", Source: "孟子", Sentence: "鱼我所欲也，熊掌亦我所欲也", Wuxing: "金", Gender: "通用"},
	{Char: "欲", Pinyin: "yù", Meaning: "欲望、想要", Source: "孟子", Sentence: "鱼我所欲也，熊掌亦我所欲也", Wuxing: "金", Gender: "通用"},
	{Char: "鱼", Pinyin: "yú", Meaning: "鱼", Source: "孟子", Sentence: "鱼我所欲也，熊掌亦我所欲也", Wuxing: "水", Gender: "通用"},
	{Char: "熊", Pinyin: "xióng", Meaning: "熊", Source: "孟子", Sentence: "鱼我所欲也，熊掌亦我所欲也", Wuxing: "水", Gender: "通用"},
	{Char: "掌", Pinyin: "zhǎng", Meaning: "手掌", Source: "孟子", Sentence: "鱼我所欲也，熊掌亦我所欲也", Wuxing: "火", Gender: "通用"},
	{Char: "得", Pinyin: "dé", Meaning: "得到、获得", Source: "孟子", Sentence: "鱼我所欲也，熊掌亦我所欲也", Wuxing: "金", Gender: "通用"},
	{Char: "舍", Pinyin: "shě", Meaning: "舍弃", Source: "孟子", Sentence: "鱼我所欲也，熊掌亦我所欲也", Wuxing: "金", Gender: "通用"},
	{Char: "生", Pinyin: "shēng", Meaning: "生命", Source: "孟子", Sentence: "生，亦我所欲也，义，亦我所欲也", Wuxing: "金", Gender: "通用"},
	{Char: "义", Pinyin: "yì", Meaning: "正义", Source: "孟子", Sentence: "生，亦我所欲也，义，亦我所欲也", Wuxing: "金", Gender: "通用"},
	{Char: "兼", Pinyin: "jiān", Meaning: "兼顾、兼得", Source: "孟子", Sentence: "二者不可得兼，舍生而取义者也", Wuxing: "金", Gender: "通用"},
	{Char: "道", Pinyin: "dào", Meaning: "道理、道路", Source: "孟子", Sentence: "得道者多助，失道者寡助", Wuxing: "火", Gender: "通用"},
	{Char: "助", Pinyin: "zhù", Meaning: "帮助", Source: "孟子", Sentence: "得道者多助，失道者寡助", Wuxing: "金", Gender: "通用"},
	{Char: "多", Pinyin: "duō", Meaning: "多", Source: "孟子", Sentence: "得道者多助，失道者寡助", Wuxing: "火", Gender: "通用"},
	{Char: "寡", Pinyin: "guǎ", Meaning: "少", Source: "孟子", Sentence: "得道者多助，失道者寡助", Wuxing: "土", Gender: "通用"},
	{Char: "民", Pinyin: "mín", Meaning: "人民、百姓", Source: "孟子", Sentence: "得道者多助，失道者寡助", Wuxing: "水", Gender: "通用"},
	{Char: "天", Pinyin: "tiān", Meaning: "天空、天意", Source: "孟子", Sentence: "得道者多助，失道者寡助", Wuxing: "火", Gender: "通用"},
	{Char: "顺", Pinyin: "shùn", Meaning: "顺利、顺应", Source: "孟子", Sentence: "天时不如地利，地利不如人和", Wuxing: "金", Gender: "通用"},
	{Char: "天", Pinyin: "tiān", Meaning: "天时", Source: "孟子", Sentence: "天时不如地利，地利不如人和", Wuxing: "火", Gender: "通用"},
	{Char: "时", Pinyin: "shí", Meaning: "时机", Source: "孟子", Sentence: "天时不如地利，地利不如人和", Wuxing: "金", Gender: "通用"},
	{Char: "地", Pinyin: "dì", Meaning: "地理、地利", Source: "孟子", Sentence: "天时不如地利，地利不如人和", Wuxing: "土", Gender: "通用"},
	{Char: "利", Pinyin: "lì", Meaning: "利益、顺利", Source: "孟子", Sentence: "天时不如地利，地利不如人和", Wuxing: "金", Gender: "通用"},
	{Char: "人", Pinyin: "rén", Meaning: "人心、人和", Source: "孟子", Sentence: "天时不如地利，地利不如人和", Wuxing: "金", Gender: "通用"},
	{Char: "和", Pinyin: "hé", Meaning: "和谐", Source: "孟子", Sentence: "天时不如地利，地利不如人和", Wuxing: "水", Gender: "通用"},
	{Char: "至", Pinyin: "zhì", Meaning: "到达、极致", Source: "孟子", Sentence: "登泰山而小天下", Wuxing: "火", Gender: "通用"},
	{Char: "泰", Pinyin: "tài", Meaning: "泰山、平安", Source: "孟子", Sentence: "登泰山而小天下", Wuxing: "水", Gender: "通用"},
	{Char: "山", Pinyin: "shān", Meaning: "高山", Source: "孟子", Sentence: "登泰山而小天下", Wuxing: "土", Gender: "通用"},
	{Char: "小", Pinyin: "xiǎo", Meaning: "小看", Source: "孟子", Sentence: "登泰山而小天下", Wuxing: "金", Gender: "通用"},
	{Char: "下", Pinyin: "xià", Meaning: "天下", Source: "孟子", Sentence: "登泰山而小天下", Wuxing: "土", Gender: "通用"},
	{Char: "观", Pinyin: "guān", Meaning: "观看、观察", Source: "孟子", Sentence: "观于海者难为水", Wuxing: "木", Gender: "通用"},
	{Char: "海", Pinyin: "hǎi", Meaning: "大海", Source: "孟子", Sentence: "观于海者难为水", Wuxing: "水", Gender: "通用"},
	{Char: "水", Pinyin: "shuǐ", Meaning: "水", Source: "孟子", Sentence: "观于海者难为水", Wuxing: "水", Gender: "通用"},
	{Char: "难", Pinyin: "nán", Meaning: "困难、难以", Source: "孟子", Sentence: "观于海者难为水", Wuxing: "火", Gender: "通用"},
	{Char: "为", Pinyin: "wéi", Meaning: "作为", Source: "孟子", Sentence: "观于海者难为水", Wuxing: "土", Gender: "通用"},
	{Char: "源", Pinyin: "yuán", Meaning: "源头、源泉", Source: "孟子", Sentence: "源泉混混，不舍昼夜", Wuxing: "水", Gender: "通用"},
	{Char: "泉", Pinyin: "quán", Meaning: "泉水", Source: "孟子", Sentence: "源泉混混，不舍昼夜", Wuxing: "水", Gender: "通用"},
	{Char: "混", Pinyin: "hùn", Meaning: "混合、浑浊", Source: "孟子", Sentence: "源泉混混，不舍昼夜", Wuxing: "水", Gender: "通用"},
	{Char: "舍", Pinyin: "shě", Meaning: "舍弃、放下", Source: "孟子", Sentence: "源泉混混，不舍昼夜", Wuxing: "金", Gender: "通用"},
	{Char: "昼", Pinyin: "zhòu", Meaning: "白天", Source: "孟子", Sentence: "源泉混混，不舍昼夜", Wuxing: "火", Gender: "通用"},
	{Char: "夜", Pinyin: "yè", Meaning: "夜晚", Source: "孟子", Sentence: "源泉混混，不舍昼夜", Wuxing: "火", Gender: "通用"},
	{Char: "盈", Pinyin: "yíng", Meaning: "充满、盈满", Source: "孟子", Sentence: "源泉混混，不舍昼夜", Wuxing: "火", Gender: "通用"},
	{Char: "科", Pinyin: "kē", Meaning: "科学、科举", Source: "孟子", Sentence: "源泉混混，不舍昼夜", Wuxing: "木", Gender: "通用"},
	{Char: "邪", Pinyin: "xié", Meaning: "邪恶", Source: "孟子", Sentence: "源泉混混，不舍昼夜", Wuxing: "金", Gender: "通用"},
	{Char: "正", Pinyin: "zhèng", Meaning: "正直、正义", Source: "孟子", Sentence: "源泉混混，不舍昼夜", Wuxing: "火", Gender: "通用"},
	{Char: "挟", Pinyin: "xié", Meaning: "挟持、倚仗", Source: "孟子", Sentence: "挟泰山以超北海", Wuxing: "金", Gender: "通用"},
	{Char: "超", Pinyin: "chāo", Meaning: "超越", Source: "孟子", Sentence: "挟泰山以超北海", Wuxing: "金", Gender: "通用"},
	{Char: "北", Pinyin: "běi", Meaning: "北方、北海", Source: "孟子", Sentence: "挟泰山以超北海", Wuxing: "水", Gender: "通用"},
	{Char: "海", Pinyin: "hǎi", Meaning: "大海", Source: "孟子", Sentence: "挟泰山以超北海", Wuxing: "水", Gender: "通用"},
	{Char: "故", Pinyin: "gù", Meaning: "原因、故意", Source: "庄子", Sentence: "彼亦一是非，此亦一是非", Wuxing: "火", Gender: "通用"},
	{Char: "是", Pinyin: "shì", Meaning: "正确、这是", Source: "庄子", Sentence: "彼亦一是非，此亦一是非", Wuxing: "金", Gender: "通用"},
	{Char: "非", Pinyin: "fēi", Meaning: "错误、不是", Source: "庄子", Sentence: "彼亦一是非，此亦一是非", Wuxing: "火", Gender: "通用"},
	{Char: "彼", Pinyin: "bǐ", Meaning: "那个、他们", Source: "庄子", Sentence: "彼亦一是非，此亦一是非", Wuxing: "水", Gender: "通用"},
	{Char: "此", Pinyin: "cǐ", Meaning: "这个、这里", Source: "庄子", Sentence: "彼亦一是非，此亦一是非", Wuxing: "火", Gender: "通用"},
	{Char: "逍遥", Pinyin: "xiāoyáo", Meaning: "逍遥自在", Source: "庄子", Sentence: "逍遥游", Wuxing: "金", Gender: "通用"},
	{Char: "游", Pinyin: "yóu", Meaning: "游玩、游历", Source: "庄子", Sentence: "逍遥游", Wuxing: "水", Gender: "通用"},
	{Char: "鲲", Pinyin: "kūn", Meaning: "鲲鹏", Source: "庄子", Sentence: "北冥有鱼，其名为鲲", Wuxing: "水", Gender: "通用"},
	{Char: "鹏", Pinyin: "péng", Meaning: "大鹏鸟", Source: "庄子", Sentence: "化而为鸟，其名为鹏", Wuxing: "火", Gender: "通用"},
	{Char: "怒", Pinyin: "nù", Meaning: "奋发、怒飞", Source: "庄子", Sentence: "怒而飞，其翼若垂天之云", Wuxing: "火", Gender: "通用"},
	{Char: "翼", Pinyin: "yì", Meaning: "翅膀", Source: "庄子", Sentence: "怒而飞，其翼若垂天之云", Wuxing: "金", Gender: "通用"},
	{Char: "垂", Pinyin: "chuí", Meaning: "下垂、垂下", Source: "庄子", Sentence: "怒而飞，其翼若垂天之云", Wuxing: "土", Gender: "通用"},
	{Char: "云", Pinyin: "yún", Meaning: "云彩", Source: "庄子", Sentence: "怒而飞，其翼若垂天之云", Wuxing: "水", Gender: "通用"},
	{Char: "志", Pinyin: "zhì", Meaning: "志向、志愿", Source: "庄子", Sentence: "燕雀安知鸿鹄之志", Wuxing: "火", Gender: "通用"},
	{Char: "鸿", Pinyin: "hóng", Meaning: "鸿雁、宏大", Source: "庄子", Sentence: "燕雀安知鸿鹄之志", Wuxing: "水", Gender: "通用"},
	{Char: "鹄", Pinyin: "hú", Meaning: "天鹅", Source: "庄子", Sentence: "燕雀安知鸿鹄之志", Wuxing: "水", Gender: "通用"},
	{Char: "雀", Pinyin: "què", Meaning: "麻雀", Source: "庄子", Sentence: "燕雀安知鸿鹄之志", Wuxing: "金", Gender: "通用"},
	{Char: "安", Pinyin: "ān", Meaning: "平安、安心", Source: "庄子", Sentence: "燕雀安知鸿鹄之志", Wuxing: "土", Gender: "通用"},
	{Char: "知", Pinyin: "zhī", Meaning: "知道、了解", Source: "庄子", Sentence: "燕雀安知鸿鹄之志", Wuxing: "火", Gender: "通用"},
	{Char: "材", Pinyin: "cái", Meaning: "木材、才能", Source: "庄子", Sentence: "无用之用，方为大用", Wuxing: "木", Gender: "通用"},
	{Char: "用", Pinyin: "yòng", Meaning: "使用、作用", Source: "庄子", Sentence: "无用之用，方为大用", Wuxing: "土", Gender: "通用"},
	{Char: "大", Pinyin: "dà", Meaning: "大的、伟大", Source: "庄子", Sentence: "无用之用，方为大用", Wuxing: "火", Gender: "通用"},
	{Char: "齐", Pinyin: "qí", Meaning: "整齐、齐备", Source: "庄子", Sentence: "天地与我并生，而万物与我为一", Wuxing: "金", Gender: "通用"},
	{Char: "物", Pinyin: "wù", Meaning: "万物、事物", Source: "庄子", Sentence: "天地与我并生，而万物与我为一", Wuxing: "水", Gender: "通用"},
	{Char: "一", Pinyin: "yī", Meaning: "统一、一致", Source: "庄子", Sentence: "天地与我并生，而万物与我为一", Wuxing: "土", Gender: "通用"},
	{Char: "并", Pinyin: "bìng", Meaning: "并且、并列", Source: "庄子", Sentence: "天地与我并生，而万物与我为一", Wuxing: "金", Gender: "通用"},
	{Char: "生", Pinyin: "shēng", Meaning: "生命、生长", Source: "庄子", Sentence: "天地与我并生，而万物与我为一", Wuxing: "金", Gender: "通用"},
	{Char: "秋", Pinyin: "qiū", Meaning: "秋天、秋季", Source: "庄子", Sentence: "秋水时至，百川灌河", Wuxing: "金", Gender: "通用"},
	{Char: "水", Pinyin: "shuǐ", Meaning: "水", Source: "庄子", Sentence: "秋水时至，百川灌河", Wuxing: "水", Gender: "通用"},
	{Char: "时", Pinyin: "shí", Meaning: "时间、时机", Source: "庄子", Sentence: "秋水时至，百川灌河", Wuxing: "金", Gender: "通用"},
	{Char: "至", Pinyin: "zhì", Meaning: "来到、到达", Source: "庄子", Sentence: "秋水时至，百川灌河", Wuxing: "火", Gender: "通用"},
	{Char: "百", Pinyin: "bǎi", Meaning: "众多、一百", Source: "庄子", Sentence: "秋水时至，百川灌河", Wuxing: "火", Gender: "通用"},
	{Char: "川", Pinyin: "chuān", Meaning: "河流、川流", Source: "庄子", Sentence: "秋水时至，百川灌河", Wuxing: "金", Gender: "通用"},
	{Char: "灌", Pinyin: "guàn", Meaning: "灌溉、灌入", Source: "庄子", Sentence: "秋水时至，百川灌河", Wuxing: "水", Gender: "通用"},
	{Char: "河", Pinyin: "hé", Meaning: "黄河、河流", Source: "庄子", Sentence: "秋水时至，百川灌河", Wuxing: "水", Gender: "通用"},
	{Char: "笃", Pinyin: "dǔ", Meaning: "深厚、坚定", Source: "中庸", Sentence: "博学之，审问之，慎思之，明辨之，笃行之", Wuxing: "木", Gender: "通用"},
	{Char: "博", Pinyin: "bó", Meaning: "广博、博学", Source: "中庸", Sentence: "博学之，审问之，慎思之，明辨之，笃行之", Wuxing: "金", Gender: "通用"},
	{Char: "学", Pinyin: "xué", Meaning: "学习、学问", Source: "中庸", Sentence: "博学之，审问之，慎思之，明辨之，笃行之", Wuxing: "水", Gender: "通用"},
	{Char: "审", Pinyin: "shěn", Meaning: "详细、审慎", Source: "中庸", Sentence: "博学之，审问之，慎思之，明辨之，笃行之", Wuxing: "金", Gender: "通用"},
	{Char: "问", Pinyin: "wèn", Meaning: "询问、提问", Source: "中庸", Sentence: "博学之，审问之，慎思之，明辨之，笃行之", Wuxing: "金", Gender: "通用"},
	{Char: "慎", Pinyin: "shèn", Meaning: "慎重、谨慎", Source: "中庸", Sentence: "博学之，审问之，慎思之，明辨之，笃行之", Wuxing: "金", Gender: "通用"},
	{Char: "思", Pinyin: "sī", Meaning: "思考、思念", Source: "中庸", Sentence: "博学之，审问之，慎思之，明辨之，笃行之", Wuxing: "金", Gender: "通用"},
	{Char: "明", Pinyin: "míng", Meaning: "明亮、明白", Source: "中庸", Sentence: "博学之，审问之，慎思之，明辨之，笃行之", Wuxing: "火", Gender: "通用"},
	{Char: "辨", Pinyin: "biàn", Meaning: "辨别、分辨", Source: "中庸", Sentence: "博学之，审问之，慎思之，明辨之，笃行之", Wuxing: "金", Gender: "通用"},
	{Char: "行", Pinyin: "xíng", Meaning: "行为、行动", Source: "中庸", Sentence: "博学之，审问之，慎思之，明辨之，笃行之", Wuxing: "金", Gender: "通用"},
	{Char: "诚", Pinyin: "chéng", Meaning: "真诚、诚实", Source: "中庸", Sentence: "诚者，天之道也", Wuxing: "金", Gender: "通用"},
	{Char: "天", Pinyin: "tiān", Meaning: "天空、天道", Source: "中庸", Sentence: "诚者，天之道也", Wuxing: "火", Gender: "通用"},
	{Char: "道", Pinyin: "dào", Meaning: "道理、道路", Source: "中庸", Sentence: "诚者，天之道也", Wuxing: "火", Gender: "通用"},
	{Char: "明", Pinyin: "míng", Meaning: "明白、光明", Source: "大学", Sentence: "大学之道，在明明德", Wuxing: "火", Gender: "通用"},
	{Char: "德", Pinyin: "dé", Meaning: "品德、德行", Source: "大学", Sentence: "大学之道，在明明德", Wuxing: "火", Gender: "通用"},
	{Char: "新", Pinyin: "xīn", Meaning: "更新、新的", Source: "大学", Sentence: "苟日新，日日新，又日新", Wuxing: "金", Gender: "通用"},
	{Char: "日", Pinyin: "rì", Meaning: "日子、每天", Source: "大学", Sentence: "苟日新，日日新，又日新", Wuxing: "火", Gender: "通用"},
	{Char: "苟", Pinyin: "gǒu", Meaning: "如果、假如", Source: "大学", Sentence: "苟日新，日日新，又日新", Wuxing: "木", Gender: "通用"},
	{Char: "止", Pinyin: "zhǐ", Meaning: "停止、终止", Source: "大学", Sentence: "知止而后有定", Wuxing: "火", Gender: "通用"},
	{Char: "定", Pinyin: "dìng", Meaning: "安定、决定", Source: "大学", Sentence: "知止而后有定", Wuxing: "火", Gender: "通用"},
	{Char: "静", Pinyin: "jìng", Meaning: "宁静、平静", Source: "大学", Sentence: "定而后能静", Wuxing: "金", Gender: "通用"},
	{Char: "安", Pinyin: "ān", Meaning: "安定、安宁", Source: "大学", Sentence: "静而后能安", Wuxing: "土", Gender: "通用"},
	{Char: "虑", Pinyin: "lǜ", Meaning: "思考、忧虑", Source: "大学", Sentence: "安而后能虑", Wuxing: "火", Gender: "通用"},
	{Char: "得", Pinyin: "dé", Meaning: "得到、获得", Source: "大学", Sentence: "虑而后能得", Wuxing: "金", Gender: "通用"},
	{Char: "格", Pinyin: "gé", Meaning: "格子、规格", Source: "大学", Sentence: "物格而后知至", Wuxing: "木", Gender: "通用"},
	{Char: "物", Pinyin: "wù", Meaning: "事物、万物", Source: "大学", Sentence: "物格而后知至", Wuxing: "水", Gender: "通用"},
	{Char: "致", Pinyin: "zhì", Meaning: "到达、致使", Source: "大学", Sentence: "物格而后知至", Wuxing: "火", Gender: "通用"},
	{Char: "知", Pinyin: "zhī", Meaning: "知道、知识", Source: "大学", Sentence: "物格而后知至", Wuxing: "火", Gender: "通用"},
	{Char: "善", Pinyin: "shàn", Meaning: "善良、善于", Source: "大学", Sentence: "止于至善", Wuxing: "金", Gender: "通用"},
	{Char: "至", Pinyin: "zhì", Meaning: "到达、极致", Source: "大学", Sentence: "止于至善", Wuxing: "火", Gender: "通用"},
	{Char: "厚", Pinyin: "hòu", Meaning: "深厚、厚道", Source: "大学", Sentence: "厚德载物", Wuxing: "水", Gender: "通用"},
	{Char: "载", Pinyin: "zài", Meaning: "承载、装载", Source: "大学", Sentence: "厚德载物", Wuxing: "金", Gender: "通用"},
	{Char: "物", Pinyin: "wù", Meaning: "万物、事物", Source: "大学", Sentence: "厚德载物", Wuxing: "水", Gender: "通用"},
}

func GetGuwenMingjuChars() []GuwenMingju {
	return GuwenMingjuChars
}

func GetGuwenMingjuCharList(gender string) []GuwenMingju {
	if gender == "" {
		return GuwenMingjuChars
	}
	var result []GuwenMingju
	for _, c := range GuwenMingjuChars {
		if c.Gender == gender || c.Gender == "通用" {
			result = append(result, c)
		}
	}
	return result
}
